services:
  - type: web
    name: render_test
    env: elixir
    buildCommand: sh ./build.sh
    startCommand: _build/prod/rel/render_test/bin/render_test start
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: COPY_TEXT
        sync: false
      - fromGroup: render_test

envVarGroups:
  - name: render_test
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: COPY_TEXT
        sync: false
